tempest_lib to tempest.lib for importing auth
Gate is failing with this error:

TypeError: credentials object is of type SolumCredentials,
which is not a valid Credentials object type.

This is happening because the auth module's location
changed.

Change-Id: I55200d6617cd8bc6561477c772d7daa7329ade52
Closes-Bug: #1551301