Quick fix for TypeError on FakePecanRequest
Some patches currently in review have the following error
TypeError: 'FakePecanRequest' object does not support item assignment
The error happens when we try to set a custom content-type
https://review.openstack.org/#/c/70168/
https://review.openstack.org/#/c/69855/

It can potentially break other coming patches

I fixed this bug in another review https://review.openstack.org/#/c/70975/
but it should not be in branches with dependent patches and get in master
the earliest.

Change-Id: I74aa9edb264c7ce8990752796d69e5faef30accb